{
  "formatVersion": "1.1",
  "component": {
    "group": "org.spongepowered",
    "module": "configurate-gson",
    "version": "4.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-gson-4.1.2.jar",
          "url": "configurate-gson-4.1.2.jar",
          "size": 19108,
          "sha512": "240b8eb6018d25da1094e516328e8cc43d7829b5fee7f7b26be2d1ad23514c618481e019dd88059e29432e8721805475426353edba12fa2d0a98f85abfd81100",
          "sha256": "ad2a0e0e01054cf516f915d2365cfe0b91b23d4f1b7e847f973d30c6b4a38397",
          "sha1": "3e5c7a0ea73e95ce6139fa72f1b6d36eb531ab81",
          "md5": "1793b3ac7ae7974d32aa39a3b2e0e1d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-gson-4.1.2.jar",
          "url": "configurate-gson-4.1.2.jar",
          "size": 19108,
          "sha512": "240b8eb6018d25da1094e516328e8cc43d7829b5fee7f7b26be2d1ad23514c618481e019dd88059e29432e8721805475426353edba12fa2d0a98f85abfd81100",
          "sha256": "ad2a0e0e01054cf516f915d2365cfe0b91b23d4f1b7e847f973d30c6b4a38397",
          "sha1": "3e5c7a0ea73e95ce6139fa72f1b6d36eb531ab81",
          "md5": "1793b3ac7ae7974d32aa39a3b2e0e1d2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configurate-gson-4.1.2-javadoc.jar",
          "url": "configurate-gson-4.1.2-javadoc.jar",
          "size": 412707,
          "sha512": "61b588e2f2aebc5db6a49218fe5b6b108a70842be3628b9da33129e9fee78866d1d9b3bd676ad703542fa26a6b754d455ec4e67f57b60f2809a77253d888137f",
          "sha256": "790f82e75588dea944cb70a637c334c588a3ca387d80a72c0282b68583a5e821",
          "sha1": "504b064c1204c93fce83ece7da6cc23dba9ff70b",
          "md5": "87e2d2956d95d8f333af26447c6d1770"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configurate-gson-4.1.2-sources.jar",
          "url": "configurate-gson-4.1.2-sources.jar",
          "size": 9451,
          "sha512": "b365c81a6795ebf3b5bd29f4e97ab1b143a8f34c77833e6ed5f154fe3f445b89b9384080e9e2158f5b5c654a793e908744f21bf1ae007983cbb20d3ee45c36ef",
          "sha256": "35e94d0f2f896892a6647997c3258c44b4b3fd51a4cdf5266c923c5c538377cf",
          "sha1": "2b543f33a3e33e68571141792514bbdec6e6fdea",
          "md5": "380c9ff0d82cdfa6af2218db98ddca7d"
        }
      ]
    }
  ]
}
