{
  "formatVersion": "1.1",
  "component": {
    "group": "net.md-5",
    "module": "bungeecord-chat",
    "version": "1.16-R0.4-deprecated+build.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        }
      ],
      "files": [
        {
          "name": "bungeecord-chat-1.16-R0.4-deprecated+build.9.jar",
          "url": "bungeecord-chat-1.16-R0.4-deprecated+build.9.jar",
          "size": 150965,
          "sha512": "fe0f92f19a46afcbbefdb37648ed52e68d334115729a700fcccaf78b16bb21cb708c6b6b090a9c434d7cecd7a608a86f8a77601fc1237a04f141ce59f79c6cdf",
          "sha256": "d5bdf513c72ab195e9ad18118367f89d5d9dd776401ba47e527d5f8d9de836a5",
          "sha1": "34a32cc95e1c5f12176cf0a8aeeff087ff8a17e0",
          "md5": "31d11ef412f49b0db16e38ade2deb0b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        }
      ],
      "files": [
        {
          "name": "bungeecord-chat-1.16-R0.4-deprecated+build.9.jar",
          "url": "bungeecord-chat-1.16-R0.4-deprecated+build.9.jar",
          "size": 150965,
          "sha512": "fe0f92f19a46afcbbefdb37648ed52e68d334115729a700fcccaf78b16bb21cb708c6b6b090a9c434d7cecd7a608a86f8a77601fc1237a04f141ce59f79c6cdf",
          "sha256": "d5bdf513c72ab195e9ad18118367f89d5d9dd776401ba47e527d5f8d9de836a5",
          "sha1": "34a32cc95e1c5f12176cf0a8aeeff087ff8a17e0",
          "md5": "31d11ef412f49b0db16e38ade2deb0b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bungeecord-chat-1.16-R0.4-deprecated+build.9-sources.jar",
          "url": "bungeecord-chat-1.16-R0.4-deprecated+build.9-sources.jar",
          "size": 37300,
          "sha512": "c9fec202b017a42544ef46fe04cb7e396af33ebd1e107097670f5cec105d70ad3f9172ca3904d6d24bd199698842c090fa6e3426077538a9f79c1a1ec867122c",
          "sha256": "cbc7d9824ccd429f5aad3290734ef0d439c0c344f4d7fbd8cf4a9c65d7c92d8a",
          "sha1": "39eaa0ff7c0b02ad8044d89f21916b29bae84528",
          "md5": "e7aa37276c9d9f0b43ed84628a0f6812"
        }
      ]
    }
  ]
}
