{
  "formatVersion": "1.1",
  "component": {
    "group": "org.spongepowered",
    "module": "configurate-core",
    "version": "4.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.leangen.geantyref",
          "module": "geantyref",
          "version": {
            "requires": "1.3.11"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-core-4.1.2.jar",
          "url": "configurate-core-4.1.2.jar",
          "size": 326457,
          "sha512": "022d4d087519c8e1a4b44bfdbea99b460fec4a46a73d0ec634b05fdca53ee9c4f58fde33c5fcb0966589221a95e5fd5dd9a548a660430aaae8821cb8c3bcc28c",
          "sha256": "bd6a7bae8b01ccccc24119f6db32f5b1bf7ca33de6586f6d9b8ecd26afe146ac",
          "sha1": "d6728b04738e73847f6a26349cf4368362feab97",
          "md5": "05e4381ad1a4a31d7cfa7ef6cd947705"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.leangen.geantyref",
          "module": "geantyref",
          "version": {
            "requires": "1.3.11"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-core-4.1.2.jar",
          "url": "configurate-core-4.1.2.jar",
          "size": 326457,
          "sha512": "022d4d087519c8e1a4b44bfdbea99b460fec4a46a73d0ec634b05fdca53ee9c4f58fde33c5fcb0966589221a95e5fd5dd9a548a660430aaae8821cb8c3bcc28c",
          "sha256": "bd6a7bae8b01ccccc24119f6db32f5b1bf7ca33de6586f6d9b8ecd26afe146ac",
          "sha1": "d6728b04738e73847f6a26349cf4368362feab97",
          "md5": "05e4381ad1a4a31d7cfa7ef6cd947705"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configurate-core-4.1.2-javadoc.jar",
          "url": "configurate-core-4.1.2-javadoc.jar",
          "size": 1119287,
          "sha512": "41f30ee44a56d5f400dc33355356022d73cc50909126e5b14d7351c2a395cdd90dd64deeca26cfe3347a146f265c211a8854f085a2e1c9fcb9f7f783de8b256f",
          "sha256": "d4033727a2c058b02b007a0c4b289a56f4034cb3ee3e2fe5ad7dd0183b35468e",
          "sha1": "e0abf3493579d272f7ad97eb7a922f8760105220",
          "md5": "7ca9039c20722d19cab4ebd1369b35ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configurate-core-4.1.2-sources.jar",
          "url": "configurate-core-4.1.2-sources.jar",
          "size": 205147,
          "sha512": "3d3ea59c720ae68fd438d6f44847ec09d36eb773fc33c45d46a0f61c4577c82b2f26039f16b247a25096188202e14d8ac54bb2586ab7e84d5f175ef339ba60ab",
          "sha256": "81447eeef9265712dec0a79b67ba670d4b190ce17510d0afb699d92e5695f0c1",
          "sha1": "69230783de78bffde633a419569f684960531f56",
          "md5": "cb1d2d38ff193c26399b83524e269bf3"
        }
      ]
    }
  ]
}
