dependencies {
    implementation(project(":framework:api"))
    implementation(project(":framework:kernel"))
    implementation(project(":platform:common"))
    implementation(project(":configurate"))
    implementation(project(":dependency:common"))
    implementation(project(":dependency:bukkit"))
    implementation(project(":storage:common"))
    implementation(project(":storage:jdbc"))
    implementation(project(":storage:json"))
    implementation(project(":registry:common"))
    implementation(project(":registry:itemsadder"))
    implementation(project(":registry:oraxen"))
    implementation(project(":registry:nexo"))
    implementation(project(":registry:mmoitems"))
    implementation(project(":registry:ecoitems"))
    implementation(project(":registry:vanilla"))

    implementation("dev.jorel:commandapi-bukkit-shade:10.1.0")
    implementation("org.spongepowered:configurate-yaml:4.2.0")
    compileOnly("me.clip:placeholderapi:2.11.6")
    compileOnly("io.papermc.paper:paper-api:1.19.4-R0.1-SNAPSHOT")
    testImplementation("io.papermc.paper:paper-api:1.19.4-R0.1-SNAPSHOT")
    testImplementation("com.mojang:brigadier:1.0.18")
    testImplementation("org.mockito:mockito-core:5.14.2")
}
